import { log } from "@/src/utils/logger";

// Topics for our satirical articles
const topics = [
    "technology",
    "science",
    "politics",
    "business",
    "lifestyle",
    "environment",
    "health",
    "education",
    "social media",
    "entertainment",
    "sports",
    "food",
    "transportation",
    "workplace",
    "relationships",
    "artificial intelligence",
    "virtual reality",
    "quantum computing",
    "blockchain",
    "cybersecurity",
    "cloud computing",
    "robotics",
    "internet of things",
    "5G networks",
    "digital privacy",
    "space exploration",
    "genetic engineering",
    "neuroscience",
    "renewable energy",
    "nanotechnology",
    "climate science",
    "biotechnology",
    "quantum physics",
    "marine biology",
    "gaming",
    "fashion",
    "art",
    "music",
    "cinema",
    "literature",
    "social movements",
    "generational divides",
    "cultural trends",
    "internet culture",
    "memes",
    "viral phenomena",
    "startups",
    "cryptocurrencies",
    "gig economy",
    "e-commerce",
    "venture capital",
    "digital marketing",
    "remote work culture",
    "corporate culture",
    "financial technology",
    "sharing economy",
    "mindfulness",
    "fitness trends",
    "diet fads",
    "self-improvement",
    "productivity hacks",
    "work-life balance",
    "mental health",
    "alternative medicine",
    "sleep optimization",
    "digital detox",
    "smart cities",
    "urban planning",
    "sustainable living",
    "digital nomads",
    "micro-mobility",
    "co-living spaces",
    "urban farming",
    "zero-waste lifestyle",
    "minimalism",
];

// Narrative angles for our stories
const angles = [
    "unexpected success",
    "comical failure",
    "absurd misunderstanding",
    "bizarre trend",
    "ridiculous solution",
    "overreaction",
    "unnecessary innovation",
    "pointless achievement",
    "ironic situation",
    "mundane event treated as extraordinary",
    "spectacular backfire",
    "unintended consequences",
    "dramatic revelation",
    "mysterious disappearance",
    "unlikely hero emerges",
    "surprising alliance",
    "accidental discovery",
    "paradoxical outcome",
    "karmic justice",
    "moral panic",
    "generational divide",
    "cultural misappropriation",
    "tech dystopia",
    "first world problems",
    "social media outrage",
    "cancel culture backfire",
    "virtue signaling gone wrong",
    "startup pivot disaster",
    "AI gone rogue",
    "blockchain solution to nothing",
    "unnecessary digitization",
    "app for everything",
    "tech bubble absurdity",
    "corporate buzzword overflow",
    "automation mishap",
    "self-improvement obsession",
    "productivity hack addiction",
    "mindfulness extremism",
    "wellness trend gone too far",
    "life-hack backfire",
    "optimization overdose",
    "digital age crisis",
    "social media dependency",
    "subscription fatigue",
    "smart device rebellion",
    "algorithm uprising",
    "zoom call chaos",
    "delivery app dependency",
    "streaming service overload",
];

// Character types that might appear
const characters = [
    "local resident",
    "scientist",
    "CEO",
    "politician",
    "influencer",
    "expert",
    "self-proclaimed guru",
    "concerned parent",
    "startup founder",
    "committee",
    "AI",
    "pet",
    "inanimate object given sentience",
    "crypto millionaire",
    "tech evangelist",
    "digital nomad",
    "robot rights activist",
    "AI ethics consultant",
    "data scientist",
    "quantum computing skeptic",
    "blockchain prophet",
    "VR addict",
    "disgruntled employee",
    "middle manager",
    "corporate consultant",
    "venture capitalist",
    "gig economy worker",
    "digital marketer",
    "productivity coach",
    "workplace culture expert",
    "content creator",
    "social media manager",
    "life coach",
    "wellness influencer",
    "mindfulness consultant",
    "biohacker",
    "digital minimalist",
    "sustainability expert",
    "sentient chatbot",
    "smart fridge",
    "automated assistant",
    "virtual influencer",
    "meme account",
    "algorithm",
    "social credit score",
    "blockchain smart contract",
    "Gen Z collective",
    "millennial task force",
    "boomer coalition",
    "AI rights group",
    "digital detox support group",
    "startup incubator",
    "reddit moderators",
    "twitter verification council",
];

// Types of events or situations
const situations = [
    "groundbreaking study",
    "new app launch",
    "viral trend",
    "revolutionary product",
    "policy change",
    "public announcement",
    "discovery",
    "invention",
    "crisis",
    "celebration",
    "protest",
    "award ceremony",
    "press conference",
    "AI malfunction",
    "data breach",
    "platform outage",
    "algorithm update",
    "virtual reality incident",
    "cyber attack",
    "blockchain fork",
    "quantum breakthrough",
    "robot uprising",
    "startup pivot",
    "corporate merger",
    "IPO disaster",
    "workplace culture initiative",
    "remote work experiment",
    "digital transformation",
    "agile methodology crisis",
    "viral challenge",
    "social media exodus",
    "cancel culture incident",
    "meme war",
    "influencer controversy",
    "platform migration",
    "digital detox movement",
    "virtual flash mob",
    "subscription service revolt",
    "smart home rebellion",
    "digital identity crisis",
    "zoom meeting disaster",
    "delivery app apocalypse",
    "streaming war casualty",
    "AI consciousness awakening",
    "virtual reality leak",
    "quantum entanglement accident",
    "blockchain paradox",
    "metaverse property dispute",
    "NFT existential crisis",
];

// Contemporary themes to reference
const contemporaryThemes = [
    "AI and automation",
    "social media addiction",
    "remote work",
    "cryptocurrency",
    "sustainability",
    "wellness trends",
    "digital privacy",
    "streaming services",
    "smart devices",
    "subscription economy",
    "metaverse",
    "viral challenges",
    "quantum supremacy",
    "web3 revolution",
    "AI consciousness",
    "digital immortality",
    "brain-computer interfaces",
    "autonomous vehicles",
    "space tourism",
    "synthetic biology",
    "cancel culture",
    "digital tribalism",
    "virtual relationships",
    "internet fame",
    "digital nomadism",
    "online authenticity",
    "virtual influence",
    "digital citizenship",
    "four-day workweek",
    "universal basic income",
    "hybrid workplaces",
    "productivity monitoring",
    "workplace surveillance",
    "automated management",
    "algorithmic hiring",
    "biohacking",
    "digital wellness",
    "mindfulness tech",
    "sleep optimization",
    "quantified self",
    "virtual therapy",
    "tech-life balance",
    "digital minimalism",
    "carbon footprint apps",
    "virtual power plants",
    "digital waste",
    "cloud computing emissions",
    "sustainable blockchain",
    "green AI",
    "eco-friendly NFTs",
];

// Additional prompt elements for more variety
const tones = [
    "deadpan serious",
    "increasingly absurd",
    "academically rigorous",
    "unnecessarily technical",
    "overly enthusiastic",
    "conspiracy theorist",
    "passive-aggressive",
    "extremely optimistic",
    "completely oblivious",
    "professionally skeptical",
];

const locations = [
    "Silicon Valley startup hub",
    "remote mountain retreat",
    "underground bunker",
    "virtual reality meetup",
    "blockchain commune",
    "AI research facility",
    "digital detox camp",
    "smart city prototype",
    "metaverse embassy",
    "quantum computing lab",
];

function getRandomElement<T>(array: T[]): T {
    return array[Math.floor(Math.random() * array.length)];
}

// function capitalizeFirstLetter(string: string): string {
//     return string.charAt(0).toUpperCase() + string.slice(1);
// }

export function generatePrompt(): string {
    const topic = getRandomElement(topics);
    const angle = getRandomElement(angles);
    const character = getRandomElement(characters);
    const situation = getRandomElement(situations);
    const theme = getRandomElement(contemporaryThemes);
    const tone = getRandomElement(tones);
    const location = getRandomElement(locations);

    // Different prompt templates for variety
    const templates = [
        `Write a ${tone} news article about a ${character} who encounters a ${angle} while dealing with ${theme} at a ${location}.`,
        `Create a news story about a ${situation} that leads to an unexpected ${angle} in the world of ${topic}, as reported by a ${character}.`,
        `Report on a ${character}'s attempt to revolutionize ${topic} through a ${situation} at ${location}, resulting in a ${angle}.`,
        `Cover a breaking news story about how a ${situation} related to ${theme} has caused a ${angle} for a ${character} in ${location}.`,
        `Write about a ${character} who claims to have solved ${topic} through a ${angle} involving ${theme}, leading to a ${situation}.`,
        `Document the chaos that unfolds when a ${character} introduces a solution for ${topic} using ${theme}, leading to an unexpected ${angle}.`,
        `Investigate why a group of ${character}s at ${location} are experiencing a collective ${angle} related to ${theme}.`,
        `Report on the controversial decision by a ${character} to address ${topic} through an unconventional ${situation}.`,
    ];

    const basePrompt = getRandomElement(templates);

    const fullPrompt = `${basePrompt}

The article should be humorous and absurd while maintaining a ${tone} news-like tone.
Include quotes from relevant parties that highlight the absurdity of the situation.
Add specific details that make the story more believable despite its ridiculousness.
Format the response as JSON with the following structure:
{
  "title": "A catchy, clickbait-style headline that captures the absurdity",
  "summary": "A brief 1-2 sentence summary that hooks the reader",
  "content": "The full article content with proper paragraphing"
}`;

    log("debug", "Generated new prompt", {
        topic,
        angle,
        character,
        situation,
        theme,
        tone,
        location,
        template: basePrompt,
    });

    return fullPrompt;
}
