"use client";
import { ArticleType } from "@/src/db/schema";
import Link from "next/link";
import { notFound, useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { Clock, ArrowLeft } from "lucide-react";

export default function ArticlePage() {
    const { id } = useParams<{ id: string }>();
    const [article, setArticle] = useState<ArticleType | null>(null);

    useEffect(() => {
        async function getArticleById(id: number) {
            console.log(`Fetching article with ID: ${id}`);
            const res = await fetch(`/api/article?id=${id}`, {
                method: "GET",
            });
            if (!res.ok) {
                notFound();
            }
            const [result] = await res.json();
            console.log(result);
            setArticle(result);
        }

        if (!id) {
            notFound();
        }

        getArticleById(parseInt(id));
    }, [id]);

    return (
        <main className="min-h-screen flex flex-col bg-gradient-to-b from-slate-950 to-slate-900">
            {/* Article Content */}
            {article && (
                <article className="container mx-auto flex-grow px-4 py-8">
                    <div
                        className="max-w-3xl mx-auto bg-slate-800/50 backdrop-blur-sm rounded-lg p-6 md:p-8 
                        border border-slate-700/50 ring-1 ring-cyan-500/10
                        animate-fade-in shadow-xl shadow-cyan-500/5"
                    >
                        {/* Article Header */}
                        <header className="mb-8">
                            <h1 className="text-3xl md:text-4xl font-bold text-white mb-4 tracking-tight">
                                {article.title}
                            </h1>
                            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-700/50 pb-4">
                                <p className="text-lg text-slate-300 italic">
                                    {article.summary}
                                </p>
                                <time className="flex items-center gap-2 text-sm text-slate-400 whitespace-nowrap">
                                    <Clock size={14} />
                                    {new Date(
                                        article.createdAt
                                    ).toLocaleDateString()}
                                </time>
                            </div>
                        </header>

                        {/* Article Body */}
                        <div
                            className="prose prose-invert prose-lg max-w-none 
                            prose-p:text-slate-300 prose-headings:text-white
                            prose-strong:text-white prose-blockquote:text-slate-300
                            prose-a:text-cyan-400 hover:prose-a:text-cyan-300"
                        >
                            {article.content
                                .split("\n\n")
                                .map((paragraph, index) => (
                                    <p
                                        key={index}
                                        className="mb-6 leading-relaxed"
                                    >
                                        {paragraph}
                                    </p>
                                ))}
                        </div>

                        {/* Article Footer */}
                        <footer className="mt-12 pt-6 border-t border-slate-700/50">
                            <div className="flex flex-col md:flex-row gap-4 justify-between items-center">
                                <Link
                                    href="/"
                                    className="flex items-center gap-2 text-cyan-400 hover:text-cyan-300 font-medium transition-colors group"
                                >
                                    <ArrowLeft
                                        size={16}
                                        className="group-hover:-translate-x-1 transition-transform"
                                    />
                                    Back to Articles
                                </Link>
                                <span className="text-slate-400 text-sm">
                                    Generated by AI
                                </span>
                            </div>
                        </footer>
                    </div>
                </article>
            )}
        </main>
    );
}
