name: Generate Hourly Article

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:      # Allow manual triggers

jobs:
  generate:
    runs-on: ubuntu-latest
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      CRON_SECRET: ${{ secrets.CRON_SECRET }}
    
    steps:
    - name: Generate Article
      run: |
        curl -X POST https://derpnews.com/api/cron/generate \
          -H "Content-Type: application/json" \
          -d "{\"secret\": \"${CRON_SECRET}\"}"
