name: Generate Hourly Article

on:
    schedule:
        - cron: "0 * * * *" # Runs every hour
    workflow_dispatch: # Allows manual triggering

jobs:
    generate:
        runs-on: ubuntu-latest
        steps:
            - name: Generate Article
              run: |
                  curl -X POST \
                  -H "Content-Type: application/json" \
                  -d '{"secret":"${{ secrets.CRON_SECRET }}"}' \
                  ${{ secrets.SITE_URL }}/api/cron/generate
