name: Generate Hourly Article

on:
    schedule:
        - cron: "0 * * * *" # Run every hour
    workflow_dispatch: # Allow manual triggers

jobs:
    generate:
        runs-on: ubuntu-latest

        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
            CRON_SECRET: ${{ secrets.CRON_SECRET }}
            SITE_URL: ${{ secrets.SITE_URL }}

        steps:
            - name: Generate Article
              run: |
                  response=$(curl -X POST ${{ secrets.SITE_URL }}/api/cron/generate \
                    -H "Content-Type: application/json" \
                    -d "{\"secret\": \"${CRON_SECRET}\"}")
                  echo "API Response: $response"
                  if echo "$response" | grep -q "error"; then
                    echo "Error detected in response"
                    exit 1
                  fi
